### ISSUE TITLE
Beam reach

### ISSUE THREAD

**Issue by 6r1d** [OgelGames/beacon#10]
We can remove beams using trons and have tons of those, so it might be convenient to use `override_item` for beam placement and set the `range` value as 7 or so.
Even if we can't place things, beams won't immediately dig pipeworks devices and will be a useful tool.

Also, `shift` + `click` can work as a punch only without calling digging.

**Comment by OgelGames** [comment]
I'm honestly confused about what you're asking here... 😕

**Comment by 6r1d** [comment]
> I'm honestly confused about what you're asking here...

Sorry about that. TL;DR: I want beacon beams, as objects, to have a long (7) range to click things and place those beams.

Example for PandoraBox: now I have a bunch of high-range multitools, which can easily break items in one click.
I don't always want things to break. Instead, I'd like to place lights nearby, switch pipeworks / mesecons nodes and do other manipulations. Beams can come to the rescue right there. Ideally, I'd like a long-reach stick / beam / etc. to switch nodes on and off, dig those slowly and so on. It requires minimal tool modification, but I haven't started by PR, because I'm not sure about beacon naming and syntax.

**Comment by OgelGames** [comment]
Ah, that sounds like a great idea, but it also should have nothing to do with beacon beams. 

I think it should either be an override for `default:stick` in `pandorabox_custom` or a separate mod that adds long sticks.

**Comment by SwissalpS** [comment]
No, stick with longer reach will not do. I won't carry around a stick just for that.
My idea was, we already have tools with long reach, but when punching e.g. injectors, the
high level tools dig them and whatever is behind them. So I proposed that when you hold sneak while using
multitool, that it would use the blunt end ie it's damage and speed are lessend while sneak (or other key) is being held.

Edit: beam with long reach is also a good idea, for placing them far away.
Edit2: the sneak modifier should apply to any tool, not just the ones with long reach. We have to figure out how to not collide with woodcutting.
