### ISSUE TITLE
Unloading and area bugs

### ISSUE THREAD

**Issue by OgelGames** [OgelGames/beacon#18]
Reported by Huhhila on pandorabox.io server:
> Recently I've seen 50-range flight beacons fail to give flight for full range more often than earlier (even without protection changes), typically right after mapblock change.

**Comment by BuckarooBanzay** [comment]
`active_block_range` is currently set to `1`, this translates to an effective player distance to about 16 to 32 nodes (i think?),
but i'm not sure how/when the engine is disabling the mapblock (and the nodetimer in it).

In my experiments the beacon worked pretty well up to 50 nodes :shrug:

**Comment by S-S-X** [comment]
I've experienced this thing few times too, also similar thing when moving to another beacon area without gaps in between.
