### ISSUE TITLE
radius is non-standard

### ISSUE THREAD

**Issue by SwissalpS** [OgelGames/beacon#2]
It is mathematically correct but not standard way of minetest radius.
Minetest radius is as follows: place beacon box, now place ten slabs in a line next to it.
Effect should hold up as long as player is over slabs. Should stop once user passes last slab border.
Currently it stops already after passing half of the last slab.

Protection logo/block is a good example of how it should be.

**Comment by OgelGames** [comment]
Thanks for picking that up :+1:
