### ISSUE TITLE
formspec incompatible with current minetest/master 

### ISSUE THREAD

**Issue by SwissalpS** [OgelGames/beacon#23]
It seems the formspecs are not compatible with current (last weeks) master branch of minetest.

Edit: the value fields just show '$fieldname' or similar and don't accept the values entered.

**Comment by OgelGames** [comment]
Looks fine to me 🤷 (built using latest commit today)
![screenshot_20230606_145510](https://github.com/OgelGames/beacon/assets/48543043/a427f9af-989d-425a-9910-2c9c7ea2643e)

**Comment by SwissalpS** [comment]
cool, I'll give it another try then.

**Comment by SwissalpS** [comment]
just built MT ~two hours ago and still get this (using pandorabox-mods)
![Captura de pantalla de 2023-06-08 19-20-43](https://github.com/OgelGames/beacon/assets/161979/d2139ba1-010a-4c02-8380-f6745ffe6145)
:

**Comment by SwissalpS** [comment]
with minimal mod set it works, so must be some other conflict

Edit: the full pandorabox mod set works fine on older MT build though.

**Comment by SwissalpS** [comment]
setting ``fs51.disable_meta_override`` to true did the trick
