### ISSUE TITLE
Beam destroys stealthnodes

### ISSUE THREAD

**Issue by S-S-X** [OgelGames/beacon#5]
> <SingingPotato> i'm a bit sad by now and don't want to build anything, the new beacon destroyed my space garden

Beacon beam will destroy activated stealthnodes and ghoststones. Maybe it should also check if node is buildable_to.

**Comment by OgelGames** [comment]
Sorry to whoever it was that lost their space garden :(

**Comment by BuckarooBanzay** [comment]
> Sorry to whoever it was that lost their space garden :(

Don't worry, could have been worse :smile:
