### ISSUE TITLE
Inventory swap bug

### ISSUE THREAD

**Issue by BuckarooBanzay** [OgelGames/beacon#9]
I you take out an existing diamond upgrade and place it over a player-inventory slot you can
put back whatever you clicked on into the upgrade slot:

<img src="https://i.imgur.com/UA0hQ2Z.png"/>

i don't have an idea (yet) how to solve that :shrug:

**Comment by OgelGames** [comment]
Hmm... I'll look into it, I'm thinking that must be considered as a `inventory_move` or `inventory_take`, because currently the code only checks on `inventory_put`.

**Comment by OgelGames** [comment]
Turns out this is an engine bug, see https://github.com/minetest/minetest/issues/4321 and https://github.com/minetest/minetest/issues/6534, which should be fixed by https://github.com/minetest/minetest/pull/9923

**Comment by BuckarooBanzay** [comment]
thanks :+1:
